/****** Object:  Table bench."SCHEMA"    Script Date: 06/03/2010 13:57:18 ******/

CREATE TABLE bench."SCHEMA"(
    "SCHEMAID" number(5,0) NOT NULL PRIMARY KEY,
    "SCHEMANAME" varchar(100) NOT NULL,
    "CREATIONDATE" date NOT NULL) ;


/****** Object:  Table bench."MATCHABLE"    Script Date: 06/03/2010 13:57:18 ******/

CREATE TABLE bench."MATCHABLE"(
    "MATCHABLEID" number(5,0) NOT NULL ,
 CONSTRAINT "PK_MATCHABLE" PRIMARY KEY ("MATCHABLEID"));

/****** Object:  Table bench."INSTANCE"    Script Date: 06/03/2010 13:57:18 ******/

CREATE TABLE bench."INSTANCE"(
    "SCHEMAID" number(5,0) NOT NULL,
    "URI" varchar(700) NOT NULL,
    "CLASS_SCHEMAID" number(5,0) NOT NULL,
    "CLASS_URI" varchar(700) NOT NULL,
    "DATASETSEQ" number(5,0) NOT NULL,
    "MATCHABLEID" number(5,0) NOT NULL,
 CONSTRAINT "PK_INSTANCE" PRIMARY KEY  
(
    "SCHEMAID",
    "URI" ,
    "DATASETSEQ" 
));
/****** Object:  Table bench."CLASS"    Script Date: 06/03/2010 13:57:18 ******/

CREATE TABLE bench."CLASS"(
    "SCHEMAID" number(5,0) NOT NULL,
    "URI" varchar(700) NOT NULL,
    "MATCHABLEID" number(5,0) NOT NULL,
 CONSTRAINT "PK_CLASS" PRIMARY KEY 
(
    "SCHEMAID" ,
    "URI" 
)
);
/****** Object:  Table bench."PROPERTY"    Script Date: 06/03/2010 13:57:18 ******/

CREATE TABLE bench."PROPERTY"(
    "SCHEMAID" int NOT NULL,
    "URI" varchar(700) NOT NULL,
    "DATATYPE" clob NULL,
 CONSTRAINT "PK_PROPERTY" PRIMARY KEY 
(
    "SCHEMAID" ,
    "URI" 
)
);

/****** Object:  Table bench."CPROPERTY"    Script Date: 06/03/2010 13:57:18 ******/

CREATE TABLE bench."CPROPERTY"(
    "CLASS_SCHEMAID" number(5,0) NOT NULL,
    "CLASS_URI" varchar(700) NOT NULL,
    "PROP_SCHEMAID" number(5,0) NOT NULL,
    "PROP_URI" varchar(700) NOT NULL,
    "MATCHABLEID" number(5,0) NOT NULL,
 CONSTRAINT "PK_CPROPERTY" PRIMARY KEY 
(
    "CLASS_SCHEMAID" ,
    "CLASS_URI" ,
    "PROP_SCHEMAID" ,
    "PROP_URI" 
)
);

/****** Object:  Table bench."DATASET"    Script Date: 06/03/2010 13:57:18 ******/

CREATE TABLE bench."DATASET"(
    "SCHEMAID" number(5,0) NOT NULL,
    "DATASETSEQ" number(5,0) NOT NULL,
    "FILENAME" clob NOT NULL,
    "PATH" clob NOT NULL,
    "DATE" date NOT NULL,
    "FILE" blob NOT NULL,
    "NAME" varchar(50) NOT NULL ,
 CONSTRAINT "PK_DATASET" PRIMARY KEY
(
    "SCHEMAID" ,
    "DATASETSEQ" 
)
) ;

/****** Object:  Table bench."ELEMENT"    Script Date: 06/03/2010 13:57:18 ******/

CREATE TABLE bench."ELEMENT"(
    "SCHEMAID" number(5,0) NOT NULL,
    "URI" varchar(700) NOT NULL,
    "LABEL" clob NULL,
    "COMMENT" clob NULL,
 CONSTRAINT "PK_ELEMENT" PRIMARY KEY 
(
    "SCHEMAID" ,
    "URI" 
)
) ;

/****** Object:  ForeignKey "FK_CLASS_ELEMENT"    Script Date: 06/03/2010 13:57:18 ******/
ALTER TABLE bench."CLASS"  ADD  CONSTRAINT "FK_CLASS_ELEMENT" FOREIGN KEY("SCHEMAID", "URI")
REFERENCES bench."ELEMENT" ("SCHEMAID", "URI");


/****** Object:  ForeignKey "FK_CLASS_MATCHABL"    Script Date: 06/03/2010 13:57:18 ******/
ALTER TABLE bench."CLASS" ADD  CONSTRAINT "FK_CLASS_MATCHABL" FOREIGN KEY("MATCHABLEID")
REFERENCES bench."MATCHABLE" ("MATCHABLEID")
ON DELETE CASCADE;

/****** Object:  ForeignKey "FK_CPROPERT_CLASS"    Script Date: 06/03/2010 13:57:18 ******/
ALTER TABLE bench."CPROPERTY"  ADD  CONSTRAINT "FK_CPROPERT_CLASS" FOREIGN KEY("CLASS_SCHEMAID", "CLASS_URI")
REFERENCES bench."CLASS" ("SCHEMAID", "URI");

/****** Object:  ForeignKey "FK_CPROPERT_MATCHABL"    Script Date: 06/03/2010 13:57:18 ******/
ALTER TABLE bench."CPROPERTY"  ADD  CONSTRAINT "FK_CPROPERT_MATCHABL" FOREIGN KEY("MATCHABLEID")
REFERENCES bench."MATCHABLE" ("MATCHABLEID")
ON DELETE CASCADE;

/****** Object:  ForeignKey "FK_CPROPERT_PROPERTY"    Script Date: 06/03/2010 13:57:18 ******/
ALTER TABLE bench."CPROPERTY"  ADD  CONSTRAINT "FK_CPROPERT_PROPERTY" FOREIGN KEY("PROP_SCHEMAID", "PROP_URI")
REFERENCES bench."PROPERTY" ("SCHEMAID", "URI");

/****** Object:  ForeignKey "FK_DATASET_SCHEMA"    Script Date: 06/03/2010 13:57:18 ******/
ALTER TABLE bench."DATASET"  ADD  CONSTRAINT "FK_DATASET_SCHEMA" FOREIGN KEY("SCHEMAID")
REFERENCES bench."SCHEMA" ("SCHEMAID");

/****** Object:  ForeignKey "FK_ELEMENT_SCHEMA"    Script Date: 06/03/2010 13:57:18 ******/
ALTER TABLE bench."ELEMENT"  ADD  CONSTRAINT "FK_ELEMENT_SCHEMA" FOREIGN KEY("SCHEMAID")
REFERENCES bench."SCHEMA" ("SCHEMAID");

/****** Object:  ForeignKey "FK_INSTANCE_CLASS"    Script Date: 06/03/2010 13:57:18 ******/
ALTER TABLE bench."INSTANCE"  ADD  CONSTRAINT "FK_INSTANCE_CLASS" FOREIGN KEY("CLASS_SCHEMAID", "CLASS_URI")
REFERENCES bench."CLASS" ("SCHEMAID", "URI");

/****** Object:  ForeignKey "FK_INSTANCE_DATASET"    Script Date: 06/03/2010 13:57:18 ******/
ALTER TABLE bench."INSTANCE"  ADD  CONSTRAINT "FK_INSTANCE_DATASET" FOREIGN KEY("SCHEMAID", "DATASETSEQ")
REFERENCES bench."DATASET" ("SCHEMAID", "DATASETSEQ");

/****** Object:  ForeignKey "FK_INSTANCE_ELEMENT"    Script Date: 06/03/2010 13:57:18 ******/
ALTER TABLE bench."INSTANCE"  ADD  CONSTRAINT "FK_INSTANCE_ELEMENT" FOREIGN KEY("SCHEMAID", "URI")
REFERENCES bench."ELEMENT" ("SCHEMAID", "URI");

/****** Object:  ForeignKey "FK_INSTANCE_MATCHABL"    Script Date: 06/03/2010 13:57:18 ******/
ALTER TABLE bench."INSTANCE"  ADD  CONSTRAINT "FK_INSTANCE_MATCHABL" FOREIGN KEY("MATCHABLEID")
REFERENCES bench."MATCHABLE" ("MATCHABLEID")
ON DELETE CASCADE;

/****** Object:  ForeignKey "FK_PROPERTY_ELEMENT"    Script Date: 06/03/2010 13:57:18 ******/
ALTER TABLE bench."PROPERTY" ADD  CONSTRAINT "FK_PROPERTY_ELEMENT" FOREIGN KEY("SCHEMAID", "URI")
REFERENCES bench."ELEMENT" ("SCHEMAID", "URI");



/****** Object:  Table "bench"."dbo]."bench"."VALIDNAMESPACE]    Script Date: 06/03/2010 13:57:18 ******/

CREATE TABLE bench."VALIDNAMESPACE"(
    "SCHEMAID" number(5,0) NOT NULL,
    "NAMESPACE" varchar(700) NOT NULL,
 CONSTRAINT "PK_VALIDNAMESPACE" PRIMARY KEY
(
    "SCHEMAID" ,
    "NAMESPACE" 
)
);


CREATE SEQUENCE sq_schemaid;


CREATE TABLE ELEMENT_INDIVIDUAL
(
    "VALUE"                VARCHAR2(4000) NULL ,
    SCHEMAID             NUMBER(5) NOT NULL ,
    URI                  VARCHAR(700) NOT NULL 
);



CREATE UNIQUE INDEX PK_ELIN ON ELEMENT_INDIVIDUAL
(SCHEMAID   ASC,URI   ASC);



ALTER TABLE ELEMENT_INDIVIDUAL
    ADD CONSTRAINT  PK_ELIN PRIMARY KEY (SCHEMAID,URI);



ALTER TABLE ELEMENT_INDIVIDUAL
    ADD (CONSTRAINT FK_ELEM_ELIN FOREIGN KEY (SCHEMAID, URI) REFERENCES ELEMENT (SCHEMAID, URI));

